# 베이스 이미지로 python:3.9-slim을 사용
FROM python:3.9-slim

# 작업 디렉토리 설정
WORKDIR /app

# 필요한 패키지 설치를 위한 requirements.txt 복사
COPY requirement.txt .

# 패키지 설치
RUN pip install --no-cache-dir -r requirement.txt

# 애플리케이션 파일 복사
COPY . .

# FastAPI 애플리케이션 실행
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
